post_install() {
	_logo='/usr/share/antergos/logo-square32.png'
	_logo_src='/usr/share/pixmaps/antergos-logo-square32.png'

	# Don't take any action on non-graphical environments
	[[ -e /usr/bin/X ]] || return 0

	[[ -e "${_logo}" ]] || [[ -e "${_logo_src}" ]] && ln -s "${_logo_src}" "${_logo}"

	/usr/bin/antergos-repo-priority.py 'True' || /usr/bin/antergos-notify.sh
}

post_upgrade() {
	post_install
}
