post_install()
{
	echo "Setting Antergos as default LightDM Theme"
	sed -i 's|greeter-session=.*|greeter-session=lightdm-webkit2-greeter|g' /etc/lightdm/lightdm.conf
	sed -i 's|#greeter-session=|greeter-session=|g' /etc/lightdm/lightdm.conf
	sed -i 's|webkit-theme=.*|webkit-theme=antergos|g' /etc/lightdm/lightdm-webkit2-greeter.conf
	find /usr/share/lightdm-webkit -type d -exec chmod 755 {} \; 

}

post_upgrade()
{
	post_install
}
