#!/bin/bash
# -*- coding: utf-8 -*-
#
#  utils.sh
#
#  Copyright © 2016-2017 Antergos
#
#  This file is part of The Antergos Build Server, (AntBS).
#
#  AntBS is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  AntBS is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  The following additional terms are in effect as per Section 7 of the license:
#
#  The preservation of all legal notices and author attributions in
#  the material or in the Appropriate Legal Notices displayed
#  by works containing it is required.
#
#  You should have received a copy of the GNU General Public License
#  along with AntBS; If not, see <http://www.gnu.org/licenses/>.


###
##
#    PACKAGE MAINTAINERS' UTILS 
##
###

THIS_DIR=$(dirname $(realpath "${BASH_SOURCE[0]}"))
GIT_ROOT=$(dirname "${THIS_DIR}")
REPO_DIR="${GIT_ROOT}/antergos"

source "${THIS_DIR}/common"


update_checksums() {
	updpkgsums && git clean -x
}

update_pkgver() {
	sed -i -E "s/(pkgver=)([0-9.]+)/\1${1}/g" PKGBUILD
}

search_replace() {
	sed -i -E "s/${1}/${2}/" PKGBUILD
} 

insert_after() {
	sed -i -E "/${1}/a ${2}" PKGBUILD
}

insert_before() {
	sed -i -E "/${1}/i ${2}" PKGBUILD
}


case $1 in

	update-checksums)
		if [[ "$2" =~ ^-g|--group$ ]]; then
			_package_group_action $3 'update_checksums'
		fi

		exit $?
	;;

	update-pkgver)
		if [[ "$2" =~ ^-g|--group$ ]]; then
			_package_group_action $3 'update_pkgver' "$4"
		fi

		exit $?
	;;

	search-replace)
		if [[ "$2" =~ ^-g|--group$ ]]; then
			_package_group_action $3 'search_replace' "$4" "$5"
		fi

		exit $?
	;;

	insert-after)
		if [[ "$2" =~ ^-g|--group$ ]]; then
			_package_group_action $3 'insert_after' "$4" "$5"
		fi

		exit $?
	;;

	insert-before)
		if [[ "$2" =~ ^-g|--group$ ]]; then
			_package_group_action $3 'insert_before' "$4" "$5"
		fi

		exit $?
	;;

	*)
		exit 0
	;;
esac

