remove_icon_cache() {
	[[ -e /var/tmp/kdecache-${USER}/icon-cache.kcache ]] || return 0
	rm /var/tmp/kdecache-${USER}/icon-cache.kcache
}

post-install() {
	case $DESKTOP_SESSION in
		kde*|*plasma*|lxqt*) 
			sed -i 's|,Adwaita|Breeze,Adwaita|g' /usr/share/icons/Numix-Square*/index.theme
			remove_icon_cache
		;;
	esac
}

post-upgrade() {
	case $DESKTOP_SESSION in
		kde*|*plasma*|lxqt*) 
			remove_icon_cache
		;;
	esac
}

post-remove() {
	post-upgrade
}

# -*- mode: bash;-*-
